In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


from sklearn.ensemble import  GradientBoostingRegressor
from sklearn.metrics import mean_squared_error as MSE
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.datasets import make_regression

In [26]:
#vamos a ir cargando los excell con los tamaños de oficnas de madrid y barcelona  
ofis= pd.read_csv(r"C:\Users\cfern\Desktop\ML Noya\oficinasBCN3.csv")
ofis.drop(["Unnamed: 0"],axis=1,inplace=True)

ofis

,ad_price,ad_area,ad_latitude,ad_longitude,censustract_id,ad_postalcode,ad_floornumber,ad_bathnumber,ad_haslift,ad_hasparkingspace,tamaños
0,23213,1451,41.397751,2.188906,801910043.0,8018.0,1,2,1,0,3
1,16000,1650,41.395914,2.139163,801905053.0,8021.0,0,0,0,0,3
2,8400,840,41.428945,2.185739,801909055.0,8027.0,3,0,1,0,3
3,72670,3116,41.399597,2.194923,801910042.0,8018.0,2,3,1,0,3
4,36301,1815,41.412205,2.207788,801910094.0,8019.0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
772,20640,860,41.387631,2.132154,801904027.0,8028.0,10,2,1,0,3
773,26977,1383,41.405259,2.208130,801910076.0,8019.0,1,6,1,0,3
774,15818,958,41.409340,2.173941,801902042.0,8025.0,0,3,0,0,3
775,17256,960,41.409040,2.173941,801902042.0,8025.0,4,2,1,0,3
776,13296,831,41.394574,2.171910,801902076.0,8010.0,1,2,0,0,3

In [27]:
X_train, X_test, y_train, y_test = train_test_split(ofis.drop('ad_price', axis=1),
                                                    ofis['ad_price'],
                                                    test_size=0.2,
                                                    random_state=42)

In [28]:
#Vamos a usar un gridsearch Cv para ver que parametros hacen mejor la regresion y usamos el RMAE como metrica del modelo para compararlo con los demas 
gb_reg = GradientBoostingRegressor()
params ={"n_estimators":[25,50,100,200],"learning_rate":[0.01,0.1,1], "max_depth":[2,3,4]}
             
grid_search= GridSearchCV (gb_reg,param_grid=params,cv=4)
grid_search.fit(X_train,y_train)

best_gb_reg = grid_search.best_estimator_
print(best_gb_reg)

y_pred = best_gb_reg.predict(X_test)

rmse = np.sqrt ( MSE(y_test, y_pred))
print("RMSE: ", rmse)
print("R^2 score test:",r2_score(y_pred, y_test))

GradientBoostingRegressor()
RMSE:  7291.92263643875
R^2 score test: 0.8991813610451828