In [10]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
from sklearn.metrics import r2_score, mean_squared_error

In [3]:
#vamos a ir cargando los excell con los tamaños de oficnas de madrid y barcelona  
ofis= pd.read_csv(r"C:\Users\cfern\Desktop\ML Noya\oficinasMAD.csv")
ofis.drop(["Unnamed: 0"],axis=1,inplace=True)

ofis

,ad_price,ad_area,ad_latitude,ad_longitude,censustract_id,ad_postalcode,ad_floornumber,ad_bathnumber,ad_haslift,ad_hasparkingspace,tamaños
0,950,83,40.441447,-3.704765,2.807907e+09,28003.0,0,1,0,0,1
1,10000,450,40.425788,-3.687349,2.807904e+09,28001.0,3,3,1,0,2
2,850,86,40.428371,-3.699201,2.807907e+09,28010.0,5,1,0,0,1
3,2000,97,40.437583,-3.623526,2.807920e+09,28037.0,3,1,0,0,1
4,2500,243,40.439797,-3.698294,2.807907e+09,28003.0,3,3,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...
5068,825,82,40.458387,-3.668784,2.807905e+09,28016.0,6,2,1,0,1
5069,3000,236,40.451402,-3.695075,2.807906e+09,28020.0,5,2,1,0,2
5070,2000,140,40.429365,-3.663276,2.807904e+09,28028.0,1,2,1,1,1
5071,2700,185,40.413855,-3.692010,2.807903e+09,28014.0,0,3,1,0,1
5072,1400,112,40.495819,-3.706806,2.807908e+09,28034.0,1,1,0,1,1

In [4]:
X_train, X_test, y_train, y_test = train_test_split(ofis.drop('ad_price', axis=1),
                                                    ofis['ad_price'],
                                                    test_size=0.2,
                                                    random_state=42)

In [8]:
#primero vamos a standariar los datos antes de aplicar el SVM construimos un pipeline 

svm_pipe = Pipeline([('scaler', StandardScaler()), ('svm', svm_reg)])

# Fit the pipeline on the training set
svm_pipe.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = svm_pipe.predict(X_test)

# Evaluate the performance of the model using R2 score and mean squared error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print('R2 score:', r2)
print('Mean squared error:', mse)

R2 score: -0.0819906486393287
Mean squared error: 287652598.3744197

In [13]:

# Define the hyperparameters to tune
param_grid = {'kernel': [ 'linear'],
              'C': [0.1, 1],
              'gamma': [ 'auto'],
              'epsilon': [0.1, 0.5]}

# asignamos a una variable el modelo SVR
svm_reg = SVR()

# hacemos la parilla con cross validation
grid_search = GridSearchCV (svm_reg, param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Train the grid search object on the training set
grid_search.fit(X_train, y_train)

# Get the best hyperparameters and score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Instantiate the SVM regressor model with the best hyperparameters
svm_reg = SVR(**best_params)

# Train the model on the training set
svm_reg.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = svm_reg.predict(X_test)

# Evaluate the performance of the model using R2 score and mean squared error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print('Best hyperparameters:', best_params)
print('Best score:', best_score)
print('R2 score:', r2)